apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: gnm3000/python-flask-hello:92dfdaa84884a0ff7801d52ddec68864d32c16b1
          ports:
            - containerPort: 8081
