apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment-prod
  labels:
    app: server-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-prod
  template:
    metadata:
      labels:
        app: server-prod
    spec:
      containers:
        - name: server-prod
          image: gnm3000/python-flask-hello-prod:92dfdaa84884a0ff7801d52ddec68864d32c16b1
          ports:
            - containerPort: 8081
