apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-client-prod
  name: mongo-client-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-client-prod
  template:
    metadata:
      labels:
        app: mongo-client-prod
    spec:
      containers:
      - image: mongo
        name: mongo-client-prod
        env:
        - name: mongo-client-prod_INITDB_ROOT_USERNAME
          value: 'dummy'
        - name: mongo-client-prod_INITDB_ROOT_PASSWORD
          value: 'dummy'
