apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-prod
  name: mongo-nodeport-svc-prod
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 30002
  selector:
    app: mongo-prod
  type: NodePort

